# Generated by Django 5.2 on 2025-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "answer",
                    models.TextField(
                        blank=True, help_text="Optional explanation or answer."
                    ),
                ),
            ],
        ),
    ]
