# Generated by Django 5.2 on 2025-06-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practicehub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AquaRatTrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("options", models.JSONField()),
                ("rationale", models.TextField(blank=True, null=True)),
                ("correct", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "db_table": "aqua_rat_train",
            },
        ),
    ]
