# Generated by Django 5.2 on 2025-06-12 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practicehub", "0002_aquarattrain"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuizAttemptDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField()),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="practicehub.userquizattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practicehub.aquarattrain",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Quiz Attempt Detail",
                "verbose_name_plural": "User Quiz Attempt Details",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
